### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by saskra** [tianrun-chen/SAM-Adapter-PyTorch#12]
What hardware did you train on? Even with 4 times 24 GB graphics cards I get the error torch.cuda.OutOfMemoryError.

**Comment by Harry-zzh** [comment]
When I test the model using batch size 1 on a V100 gpu, it raises the OutOfMemory error.

**Comment by tianrun-chen** [comment]
Hello! We use 4xA100 (80G) for training as we mentioned in the manuscript and in the readme file. The SAM model consume much memory. You can try to reduce the batch size for smaller memory consumption. Moreover, we have updated the config file so that you may use ViT-L or ViT-B version of SAM for testing, which consume less memory.

**Comment by tianrun-chen** [comment]
> When I test the model using batch size 1 on a V100 gpu, it raises the OutOfMemory error.

Hello! We use 4xA100 (80G) for training as we mentioned in the manuscript and in the readme file. The SAM model consume much memory. You can try to reduce the batch size for smaller memory consumption. Moreover, we have updated the config file so that you may use ViT-L or ViT-B version of SAM for testing, which consume less memory.

**Comment by saskra** [comment]
Thanks for the info, that's quite a memory to have. Has anyone tried this on AWS?
