### ISSUE TITLE
Fine-tuning a 3d segmentation model for medical applications.

### ISSUE THREAD

**Issue by redwangwangwang** [tianrun-chen/SAM-Adapter-PyTorch#93]
Hello, thank you for your excellent work! I modified your adapter from 2D to 3D. I used it to fine-tune a 3D segmentation model in the medical field. However, I did not get any performance improvement, and the training speed was even slower than fine-tuning all parameters. Regarding performance, my guess is that I don't have a good optimizer strategy. Does this model require a strict optimizer strategy?

**Comment by tianrun-chen** [comment]
Is it because your dataset is too small? or the input "prior knowledge" is not appropriate? We introduce a frequency and a patch-based "prior knowledge" into the adapter, but this may not be the perfect choice for 3D medical application. You are welcome to check another of our work here https://github.com/tianrun-chen/xLSTM-UNet-PyTorch
